### ISSUE TITLE
No default OpenFlow controller found for default switch!

### ISSUE THREAD

**Issue by tuxx42** [iwaseyusuke/docker-mininet#1]
There doesn't seem to be support for spawning the openvswitch-controller, so the setup defaults back to bridge mode.

```
root@a5e1cbd71ce8:~# mn
*** No default OpenFlow controller found for default switch!
*** Falling back to OVS Bridge
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller

*** Starting 1 switches
s1 ...
*** Starting CLI:
mininet> dump
<Host h1: h1-eth0:10.0.0.1 pid=87> 
<Host h2: h2-eth0:10.0.0.2 pid=89> 
<OVSBridge s1: lo:127.0.0.1,s1-eth1:None,s1-eth2:None pid=94> 
```

**Comment by iwaseyusuke** [comment]
@tuxx42 Thank you for using this Docker image!

Mininet uses [`ovs-testcontroller`](http://www.openvswitch.org/support/dist-docs/ovs-testcontroller.8.txt) as the default controller if you omit `--controller` option, but this image does not contain `ovs-testcontroller`. This image suppose to use the "remote" controller with `--controller remote[,ip=<ip>][,port=<port>]` option in order to test your own OpenFlow controller implementation (e.g. Ryu, OpenDaylight,...) on other containers or Docker host.

**Comment by iwaseyusuke** [comment]
Also, if you need to use OVS with the bridge mode, you can use `--switch ovsbr` option.

```text
root@e8823147f98e:~# mn --switch ovsbr
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller

*** Starting 1 switches
s1 ...
*** Starting CLI:
mininet> 
```

**Comment by tuxx42** [comment]
okay, i was looking for a self contained solution with a controller... but that makes sense i guess. thanks for clarifying.. feel free to close :+1:

**Comment by iwaseyusuke** [comment]
On my another repo [docker-ryu-mininet](https://github.com/iwaseyusuke/docker-ryu-mininet/blob/master/Dockerfile), Ryu controller is composed within the same container by using this image as the base image. I hope it should be helpful for you.

**Comment by Thaodtt12** [comment]
excuse me, please explain for me about that. When I setup mininet I see it, too. But I dont understand so I cant solve my problem. thanks for reading

**Comment by iwaseyusuke** [comment]
@inseo3003 Hi,
As explain on https://github.com/iwaseyusuke/docker-mininet/issues/1#issuecomment-387583764, I wrote this image for developing Ryu SDN Controller. So when I using this image, I always specify `—remote-controller` option, then the default controller should not be required.
If you need to run Mininet with the default controller, please install [`ovs-testcontroller`](http://www.openvswitch.org/support/dist-docs/ovs-testcontroller.8.txt) after starting this container.

**Comment by iwaseyusuke** [comment]
The commit https://github.com/iwaseyusuke/docker-mininet/commit/32aa41703aeec83f044b4bbbe8daa798458034c7 includes `ovs-testcontroller`. This problem should be solved with the latest image.

**Comment by akrami6194** [comment]
hello
How to fix the message "No default OpenFlow controller found for default switch" in mininet

**Comment by iwaseyusuke** [comment]
Hi @akrami6194 
Because it is the behavior of Mininet, I don’t know the details, but iI don’t think the message "No default OpenFlow controller found for default switch!" is always a kind of error.

On the Mininet's repo, "mn" command seems to output this message when you run "mn" without any "--controller" option.

https://github.com/mininet/mininet/blob/57294d013e780cccc6b4b9af151906b382c4d8a7/bin/mn#L342-L356

```text
  --controller=CONTROLLER
                        default|none|nox|ovsc|ref|remote|ryu[,param=value...]
                        ovsc=OVSController none=NullController
                        remote=RemoteController default=DefaultController
                        nox=NOX ryu=Ryu ref=Controller
```
